export { default as BottomPanel } from './BottomPanel.vue'
export { default as DesktopPanel } from './DesktopPanel.vue'
export { default as PanelContent } from './PanelContent.vue'
export { default as SidePanel } from './SidePanel.vue'
export { default as PanelLoader } from './PanelLoader.vue'
export { default as DesktopPanelLoader } from './DesktopPanelLoader.vue'
